name: Build and Publish ASP.NET 4.8 WebForms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore CICDProj/CICDProj/CICDProj.sln -PackagesDirectory CICDProj/packages

      - name: Install WebDeploy (Required for WebForms Publishing)
        run: choco install webdeploy -y --no-progress

      - name: Build solution
        run: |
            # Create absolute path to avoid any confusion
            $publishPath = "${{ github.workspace }}/published"
            mkdir $publishPath 

            msbuild CICDProj/CICDProj/CICDProj.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:publishUrl="${{ github.workspace }}/published" `
            /p:DeleteExistingFiles=True `
            /p:PrecompileBeforePublish=true `
            /verbosity:detailed

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: published/