name: Build and Publish ASP.NET 4.8 WebForms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore CICDProj/CICDProj/CICDProj.sln -PackagesDirectory CICDProj/packages

      - name: Install WebDeploy (Required for WebForms Publishing)
        run: choco install webdeploy -y --no-progress

      - name: Build solution
        run: |
            # Get commit hash (7 characters)
            $commitHash = git rev-parse --short HEAD
    
            # Create versioned output directory
            $publishDir = "publish_${{ github.ref_name }}_$commitHash"            
            mkdir $publishDir

            msbuild CICDProj/CICDProj/CICDProj.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:publishUrl="$publishDir" `
            /p:DeleteExistingFiles=True `
            /p:PrecompileBeforePublish=true `
            /verbosity:detailed `

            # Create zip (PowerShell cross-platform method)
            Compress-Archive -Path "$publishDir/*" -DestinationPath "WebFormsApp_${{ github.ref_name }}_$commitHash.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webforms-app-zip
          path: WebFormsApp_*.zip