name: Build and Publish ASP.NET 4.8 WebForms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore CICDProj/CICDProj/CICDProj.sln

      - name: Build solution
        run: |
            & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" CICDProj/CICDProj/CICDProj.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:PublishUrl="${{ github.workspace }}\published" `
            /p:PrecompileBeforePublish=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: published/