name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Restore NuGet packages
      run: msbuild /t:Restore CICDProj/CICDProj/CICDProj.sln
    
    - name: Build project
      run: msbuild CICDProj/CICDProj/CICDProj.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=../BuildOutput
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: BuildOutput

  publish:
    name: Publish
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: BuildOutput
    
    - name: Create publish directory
      run: |
        if (Test-Path 'Publish') { Remove-Item 'Publish' -Recurse -Force }
        New-Item 'Publish' -ItemType Directory
        Copy-Item -Path BuildOutput\* -Destination Publish -Recurse
    
    - name: Create ZIP archive
      run: Compress-Archive -Path Publish\_PublishedWebsites -DestinationPath CICDProj_${{ github.sha }}.zip
    
    - name: Upload publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: CICDProj-package
        path: CICDProj_${{ github.sha }}.zip
        retention-days: 7