name: Build and Publish ASP.NET 4.8 WebForms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore CICDProj/CICDProj/CICDProj.sln

      - name: Install WebDeploy
        run: choco install webdeploy -y --no-progress

      - name: Build and Publish
        run: |
          $publishPath = "${{ github.workspace }}\PublishOutput"
          mkdir $publishPath -Force
          
          msbuild CICDProj/CICDProj/CICDProj.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:PublishProfile=FolderProfile `
            /p:publishUrl="$publishPath" `
            /p:DeleteExistingFiles=True `
            /p:PrecompileBeforePublish=true `
            /p:VisualStudioVersion=16.0 `
            /verbosity:diagnostic
          
          # Debug: List published files
          dir "$publishPath" /s

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: webforms-app
          path: PublishOutput\